In [3]:
from git.repo.base import Repo
Repo.clone_from("https://github.com/PhonePe/pulse.git","C:/Users/Local User/PycharmProjects/pythonProject/Phonepe_pulse")

In [4]:
import pandas as pd
import mysql.connector as sql
import streamlit as st
import plotly.express as px
import os
import json
from streamlit_option_menu import option_menu
from PIL import Image

In [8]:
agg1 = "C:/Users/Local User/PycharmProjects/pythonProject/Phonepe_pulse/data/aggregated/transaction/country/india/state/"
agg_trans_list = os.listdir(agg1)

cols1 = {'State': [], 'Year' : [], 'Quarter' : [], 'Transaction_type': [], 'Transaction_count': [], 'Transaction_amount': [] }

for state in agg_trans_list:
  cur_state = agg1 + state + "/"
  agg_year_list = os.listdir(cur_state)

  for year in agg_year_list :
    cur_year = cur_state + year + "/"
    agg_file_list = os.listdir(cur_year)

    for file in agg_file_list :
      cur_file = cur_year + file
      data = open(cur_file, 'r')
      A = json.load(data)

      for i in A['data']['transactionData']:
        name = i['name']
        count = i['paymentInstruments'][0]['count']
        amount = i['paymentInstruments'][0]['amount']
        cols1['Transaction_type'].append(name)
        cols1['Transaction_count'].append(count)
        cols1['Transaction_amount'].append(amount)
        cols1['State'].append(state)
        cols1['Year'].append(year)
        cols1['Quarter'].append(int(file.strip('.json')))

df_agg_trans = pd.DataFrame(cols1)

In [9]:
df_agg_trans.shape

(3954, 6)

In [10]:
agg2 = "C:/Users/Local User/PycharmProjects/pythonProject/Phonepe_pulse/data/aggregated/user/country/india/state/"
agg_user_list = os.listdir(agg2)

cols2 = {'State': [], 'Year' : [], 'Quarter' : [], 'Brands': [], 'Count': [], 'Percentage': [] }

for state in agg_user_list:
  cur_state = agg2 + state + "/"
  agg_year_list = os.listdir(cur_state)

  for year in agg_year_list :
    cur_year = cur_state + year + "/"
    agg_file_list = os.listdir(cur_year)

    for file in agg_file_list :
      cur_file = cur_year + file
      data = open(cur_file, 'r')
      B = json.load(data)

      try:
        for i in B['data']['usersByDevice']:
          brand_name = i['brand']
          counts = i['count']
          percents = i['percentage']
          cols2['Brands'].append(brand_name)
          cols2['Count'].append(counts)
          cols2['Percentage'].append(percents)
          cols2['State'].append(state)
          cols2['Year'].append(year)
          cols2['Quarter'].append(int(file.strip('.json')))
      except:
        pass

df_agg_user = pd.DataFrame(cols2)

In [11]:
df_agg_user

                          State  Year  Quarter   Brands    Count  Percentage
0     andaman-&-nicobar-islands  2018        1   Xiaomi     1665    0.247033
1     andaman-&-nicobar-islands  2018        1  Samsung     1445    0.214392
2     andaman-&-nicobar-islands  2018        1     Vivo      982    0.145697
3     andaman-&-nicobar-islands  2018        1     Oppo      501    0.074332
4     andaman-&-nicobar-islands  2018        1  OnePlus      332    0.049258
...                         ...   ...      ...      ...      ...         ...
6727                west-bengal  2022        1   Lenovo   330017    0.015056
6728                west-bengal  2022        1  Infinix   284678    0.012987
6729                west-bengal  2022        1     Asus   280347    0.012790
6730                west-bengal  2022        1    Apple   277752    0.012671
6731                west-bengal  2022        1   Others  2196334    0.100199

[6732 rows x 6 columns]

In [16]:
map1 = "C:/Users/Local User/PycharmProjects/pythonProject/Phonepe_pulse/data/map/transaction/hover/country/india/state/"
map_trans_list = os.listdir(map1)

cols3 = {'State': [], 'Year' : [], 'Quarter' : [], 'District': [], 'Count': [], 'Amount': [] }

for state in map_trans_list:
  cur_state = map1 + state + "/"
  map_year_list = os.listdir(cur_state)

  for year in map_year_list :
    cur_year = cur_state + year + "/"
    map_file_list = os.listdir(cur_year)

    for file in map_file_list :
      cur_file = cur_year + file
      data = open(cur_file, 'r')
      C = json.load(data)

      for i in C['data']['hoverDataList']:
        district = i['name']
        count = i['metric'][0]['count']
        amount = i['metric'][0]['amount']
        cols3['District'].append(district)
        cols3['Count'].append(count)
        cols3['Amount'].append(amount)
        cols3['State'].append(state)
        cols3['Year'].append(year)
        cols3['Quarter'].append(int(file.strip('.json')))

df_map_trans = pd.DataFrame(cols3)

In [17]:
map2 = "C:/Users/Local User/PycharmProjects/pythonProject/Phonepe_pulse/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(map2)

cols4 = {'State': [], 'Year' : [], 'Quarter' : [], "District" : [] , 'RegisteredUser': [], 'AppOpens': [] }

for state in map_user_list:
  cur_state = map2 + state + "/"
  map_year_list = os.listdir(cur_state)

  for year in map_year_list :
    cur_year = cur_state + year + "/"
    map_file_list = os.listdir(cur_year)

    for file in map_file_list :
      cur_file = cur_year + file
      data = open(cur_file, 'r')
      C = json.load(data)

      for i in C['data']['hoverData'].items():
        district = i[0]
        registereduser = i[1]['registeredUsers']
        appOpens = i[1]['appOpens']
        cols4['District'].append(district)
        cols4['RegisteredUser'].append(registereduser)
        cols4['AppOpens'].append(appOpens)
        cols4['State'].append(state)
        cols4['Year'].append(year)
        cols4['Quarter'].append(int(file.strip('.json')))

df_map_user = pd.DataFrame(cols4)

In [18]:
top1 = "C:/Users/Local User/PycharmProjects/pythonProject/Phonepe_pulse/data/top/transaction/country/india/state/"
top_trans_list = os.listdir(top1)

cols5 = {'State': [], 'Year' : [], 'Quarter' : [], 'Pincode': [], 'Transaction_count': [], "Transaction_amount": [] }

for state in top_trans_list:
  cur_state = top1 + state + "/"
  top_year_list = os.listdir(cur_state)

  for year in top_year_list :
    cur_year = cur_state + year + "/"
    top_file_list = os.listdir(cur_year)

    for file in top_file_list :
      cur_file = cur_year + file
      data = open(cur_file, 'r')
      E = json.load(data)

      for i in E['data']['pincodes']:
        name = i['entityName']
        count = i['metric']['count']
        amount = i['metric']['amount']
        cols5['Pincode'].append(name)
        cols5['Transaction_count'].append(count)
        cols5['Transaction_amount'].append(amount)
        cols5['State'].append(state)
        cols5['Year'].append(year)
        cols5['Quarter'].append(int(file.strip('.json')))

df_top_trans = pd.DataFrame(cols5)

In [19]:
top2 = "C:/Users/Local User/PycharmProjects/pythonProject/Phonepe_pulse/data/top/user/country/india/state/"
top_user_list = os.listdir(top1)

cols6 = {'State': [], 'Year' : [], 'Quarter' : [], 'Pincode': [], "RegisteredUsers": [] }

for state in top_user_list:
  cur_state = top2 + state + "/"
  top_year_list = os.listdir(cur_state)

  for year in top_year_list :
    cur_year = cur_state + year + "/"
    top_file_list = os.listdir(cur_year)

    for file in top_file_list :
      cur_file = cur_year + file
      data = open(cur_file, 'r')
      F = json.load(data)

      for i in F['data']['pincodes']:
        name = i['name']
        registeredUsers = i['registeredUsers']
        cols6['Pincode'].append(name)
        cols6['RegisteredUsers'].append(registeredUsers)
        cols6['State'].append(state)
        cols6['Year'].append(year)
        cols6['Quarter'].append(int(file.strip('.json')))

df_top_user = pd.DataFrame(cols6)

In [20]:
df_agg_trans.to_csv('agg_trans.csv',index= False)
df_agg_user.to_csv('agg_user.csv',index= False)
df_map_trans.to_csv('map_trans.csv',index= False)
df_map_user.to_csv('map_user.csv',index= False)
df_top_trans.to_csv('top_trans.csv',index= False)
df_top_user.to_csv('top_user.csv',index= False)